### ISSUE TITLE
Reduce time-to-value in the Quick Start

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-docs#105]
I think we should try to speed the user's journey to the last step of the Quick Start as much as possible. I think we can do this in a couple ways:

1. Simplify the "Create your Vectara account" section. The UI for creating an account is fairly self-explanatory so maybe this just needs to be a link?
2. Move the "View your customer ID" section somewhere else. Maybe it can be in a "Next steps" section that guides the user to build an app, located at the bottom?

**Comment by pwoznic** [comment]
Fixed with PR 112.
