### ISSUE TITLE
Rename "Administrative Console" -> "Vectara Console"

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-docs#116]
Looks like the nav still uses the old term. Maybe we can do a "Find all" to find all references to "administrative" and replace it globally.

![image](https://github.com/vectara/vectara-docs/assets/1238659/551a43d1-af33-41a8-8d3c-df165c3e4d02)

**Comment by pwoznic** [comment]
Created PR 118 with relabeling
