### ISSUE TITLE
Document third-party integrations

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-docs#121]
For example with [LangChain](https://www.google.com/search?q=vectara+langchain&rlz=1C5GCEM_en&oq=vectara+langchain&gs_lcrp=EgZjaHJvbWUqBwgAEAAYgAQyBwgAEAAYgAQyBggBEEUYOTIGCAIQRRg8MgYIAxBFGDwyBggEEEUYPNIBCDE4MDJqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8), [LlamaIndex](https://www.google.com/search?q=vectara+llamaindex&sca_esv=575974643&rlz=1C5GCEM_en&ei=ayc3ZfWXOcu7qtsPoNme6A0&ved=0ahUKEwi1-ZqqzY2CAxXLnWoFHaCsB90Q4dUDCBA&uact=5&oq=vectara+llamaindex&gs_lp=Egxnd3Mtd2l6LXNlcnAiEnZlY3RhcmEgbGxhbWFpbmRleDIFECEYoAFI7g9QggVY5gxwAngBkAEAmAHAAaAB1wuqAQQwLjEwuAEDyAEA-AEBwgIKEAAYRxjWBBiwA8ICBxAAGIoFGEPCAgUQABiABMICChAuGIAEGOUEGArCAgcQABiABBgKwgIHEAAYDRiABMICBhAAGB4YDcICCBAAGB4YDRgPwgIIEAAYBRgeGA3CAggQABgIGB4YDcICChAAGAgYHhgNGAriAwQYACBBiAYBkAYI&sclient=gws-wiz-serp), and [Flowise](https://www.google.com/search?q=vectara+flowise&rlz=1C5GCEM_en&oq=vectara+flowise&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIKCAEQABixAxiABDINCAIQABiDARixAxiKBTITCAMQLhiDARjHARixAxjRAxiABDINCAQQABiDARixAxiABDIGCAUQRRg8MgYIBhBFGDwyBggHEEUYPNIBCDE0MzZqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8).

**Comment by eskibars** [comment]
This was done in https://docs.vectara.com/docs/sample-vectara-apps.  Closing
