### ISSUE TITLE
Low contrast for code snippets.

### ISSUE THREAD

**Issue by amin2718** [vectara/vectara-docs#170]
### Pages

https://docs.vectara.com/docs/api-reference/indexing-apis/file-upload/format-for-upload

### Description

The contrast between the background and tag name is very low, making it hard to read.

![image](https://github.com/vectara/vectara-docs/assets/83042956/2c9eb080-125e-4d31-9cb8-19676bae80d9)

**Comment by pwoznic** [comment]
The dark mode was updated at some point and now should be better:

![image](https://github.com/user-attachments/assets/6044bfee-081b-4c8a-9f56-38703b211763)

**Comment by eskibars** [comment]
Closing as completed
