### ISSUE TITLE
Make search more prominent

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-docs#172]
We can help users notice this functionality by increasing the font size, adding a primary button, and moving it to the right

![image](https://github.com/vectara/vectara-docs/assets/1238659/64dfc92d-8ee2-4877-b3bf-04af5b604a63)

![image](https://github.com/vectara/vectara-docs/assets/1238659/9b545d57-abf4-42de-8bbf-9c7d5f3b3571)

**Comment by eskibars** [comment]
To me, the fact that it's on the left is also burying it a bit.  Central or right-aligned makes more sense to me (maybe because it's more common in docusaurs docs pages, e.g. https://python.langchain.com/docs/get_started/introduction)
