### ISSUE TITLE
Choose one term and use it consistently: JWT or OAuth 2.0

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-docs#174]
This is important for folks who are trying to decide between API Keys and JWT. We can help them find the information they need if we can consistently frame it as either a choice between "API Keys vs JWTs" or "API Keys vs OAuth" but if we surface both of these in the UI it sounds like there are more than two options for folks who aren't familiar with JWT and OAuth.

![image](https://github.com/vectara/vectara-docs/assets/1238659/240265d0-06e3-4062-86d1-14364d93cc69)

**Comment by forrestbao** [comment]
I second this.

**Comment by amin2718** [comment]
The more correct term is OAuth 2.0. JWT is more of an implementation detail, and OAuth 2.0 is not backward compatible with 1.0, hence why it would be better to share the version.

**Comment by forrestbao** [comment]
Maybe just "Bearer token"?  It is widely used in many web APIs  and users are very clear on its meaning.

**Comment by eskibars** [comment]
The problem with "Bearer token" is the same as using "OAuth 2.0". It's not *inaccurate* but it's not detailed enough for enterprises. A bearer token doesn't *need* to be in JWT form: a bearer token could be a random hex string (not terribly uncommon). JWT is more (useful) detail because it describes to a user how to parse it

**Comment by amin2718** [comment]
Hi Shane, it sounds like you've thought this through pretty thoroughly. Everything you've written sounds fine.

> to call out that we use OAuth 2.0 with a client_credentials grant, and that we use JWT "Bearer" tokens in the implementation

We can mention client_credentials grant, but we should avoid the suggestion that the platform limits customers to the client_credentials grant. Our API also supports Authorization Code Grants (wherein authentication is delegated to a third-party service like Google, a company's Okta instance, etc.), which we've taken advantage of for demos in the past, and I expect more customers will take advantage of in the future.

I know we recently removed the ability to create these directly from our console UI.
