### ISSUE TITLE
File Upload API Definition does not document return values

### ISSUE THREAD

**Issue by amin2718** [vectara/vectara-docs#177]
### Pages

https://docs.vectara.com/docs/api-reference/indexing-apis/file-upload/file-upload

### Description

The File Upload API page contains incorrect information about the server return values. Crucially, it neglects to document how the request’s quota consumption is conveyed in the response.

It should also cover the interpretation of the situation wherein a 409 or 507 return code is sent along with quota consumption information.

**Comment by eskibars** [comment]
Can you provide some more details and/or point in the direction of the source of truth for these?  I was the one that crafted the OpenAPI spec for this, and I did so by taking https://docs.vectara.com/docs/api-reference/indexing-apis/file-upload/file-upload#response-codes and converting it into OAS form.  If the return HTTP codes are incorrect, they're incorrect in both places.  If the return content schema is incorrect, that can be fixed, but we'd need a source of truth for the return schema so we can turn it into OpenAPI spec format (maybe @tallatshafaat can help with that?).  We can add the schema for 200 response codes now easily, but I'd call that more of an enhancement than a bug

**Comment by amin2718** [comment]
Hi Shane,

I think @tallatshafaat can help with the details on this one. I didn't mean to suggest that the return codes are incorrect (I haven't checked). 

> It should also cover the interpretation of the situation wherein a 409 or 507 return code is sent along with quota consumption information.

When a 409 or 507 code is returned, the platform still returns the quota consumption stanza in the response. However, it indicates how much quota _would have been consumed_ by the document had it been stored in the system, not how much was actually consumed, which is zero.

**Comment by eskibars** [comment]
@pwoznic it looks like this should be closed as completed.  Can you confirm?
