### ISSUE TITLE
IndexDocument API docs are out of date

### ISSUE THREAD

**Issue by amin2718** [vectara/vectara-docs#190]
### Pages

https://docs.vectara.com/docs/api-reference/indexing-apis/indexing

### Description

![image](https://github.com/vectara/vectara-docs/assets/83042956/b5400a2c-35a7-42ca-9e35-c14c0a25fa34)

These assertions were true until June 2022, but are no longer true. The current definition is:

```
message IndexDocumentResponse {
  // If ALREADY_EXISTS, it means the document was already indexed, and no new quota was consumed.
  Status status = 1;

  // The storage quota needed for the document indexed in the request.
  // If "status" is ALREADY_EXISTS, it means that the document was already in the index prior to
  // this request. In such cases, quota is not consumed again and the value in this field
  // represents the quota consumed when the document was indexed the first time.
  StorageQuota quota_consumed = 2;
}
```

Also, the docs don't account for instant indexing. In most cases, the data is available for query serving in <1 second. When the documentation was written, the delay was up to 5 minutes.

**Comment by amin2718** [comment]
I agree that it's hard to keep the snippets updated all the time. Given the underlying system is React, it should be possible for Deryk or someone to create a custom tag that pulls the definition of any protobuf into a nicely formatted code listing:

```
<ProtobufListing name="indexing.IndexDocumentResponse>
```

Barring some kind of effort like that, we'll have to remove snippets from page. That does have the downside that users end up jumping back and forth between our long-form documentation and some other source code browser to fully understand what's going on.

Anyway, your call on the code snippets. In any case, the narrative text that explains how to make the indexing request and interpret the response is also incorrect.

**Comment by amin2718** [comment]
Here's a concrete example where I can't point a customer to our docs to help diagnose the root cause of an indexing issue, because this document is out of date.

![image](https://github.com/vectara/vectara-docs/assets/83042956/03f4e67c-efb4-4f8b-a762-965a98dd1f2c)

What I'd like to ask them is to report to me the breakdown of text vs metadata when indexing the problematic pdf.

**Comment by amin2718** [comment]
This came up again today from a different potential customer. Play.ht. They were asking whether there is any way to know how much space an indexed document is taking up. I had to explain that our index API returns this information, but the documentation is simply not up to date.

**Comment by eskibars** [comment]
@pwoznic I think this can be closed, since the gRPC definitions were pulled out of the docs.  Is that accurate?
