### ISSUE TITLE
File Upload API Definition missing information about how the document id is set

### ISSUE THREAD

**Issue by amin2718** [vectara/vectara-docs#210]
### Idea

https://docs.vectara.com/docs/api-reference/indexing-apis/file-upload/file-upload

The file upload API documentation doesn't provide any guidance on how to set the document id in our system. This is a serious omission given the centrality of the id.

The id is taken from the `Content-Disposition` header. The value corresponding to the `filename` key is extracted.

Reference: https://bitbucket.org/zir-ai/platform/src/aaca4a16b19d55a35325318f3a04efb919febfec/indexing/titan/src/main/java/com/vectara/indexer/baobab/FileUploadServlet.java#lines-659

Context: Engineers at play.ht were confused and couldn't find guidance in our docs.

**Comment by amin2718** [comment]
@eskibars lmk if you want me know if/how you want me to set the Assignee field.

**Comment by amin2718** [comment]
Feedback from the customer:

> Great. If the filename was being passed in the upload file example in the documentation, it would have helped. I'm talking about [this page](https://docs.vectara.com/docs/getting-started-samples/upload_file.js) for example.

**Comment by eskibars** [comment]
@pwoznic watches this repo.  He'll self-assign or assign to someone else if he needs

**Comment by amin2718** [comment]
Here's the standard docs for Content-Disposition for anyone who wants to learn more: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

**Comment by pwoznic** [comment]
Amin provided great context on the missing info and play.ht use case and I am reaching out to the team where help is needed
