### ISSUE TITLE
"Format a Python Document" makes no sense to me

### ISSUE THREAD

**Issue by amin2718** [vectara/vectara-docs#249]
### Pages

https://docs.vectara.com/docs/api-reference/indexing-apis/file-upload/format-for-upload

### Description

I'm having trouble understanding the meaning of the words "Format a Python Document"

![image](https://github.com/vectara/vectara-docs/assets/83042956/8f8f827c-29db-4b58-a322-f96148cfaab5)

The table of contents also doesn't make sense. It suggests that "Python Document" is a format that our system accepts.

![image](https://github.com/vectara/vectara-docs/assets/83042956/d68b19fe-5bab-4553-8bac-adae1a767018)

**Comment by pwoznic** [comment]
Thank you for pointing this out. The original names for these subheadings were "Sample JSON Document," "Sample Python Document," etc and they were changed during one of the IA/label updates. I can change them back to the original subheadings.

**Comment by amin2718** [comment]
On my phone so excuse the benefit.
The python is code, not a document. It is python code that creates the
document shown in the previous section. Makes sense?

Amin

**Comment by pwoznic** [comment]
Yes, thank you I'll make the change. Should I remove the Pbtext section as well? I remember hearing something about pbtext but not sure if it was keep or remove.

**Comment by amin2718** [comment]
Hi Paul,

The Pbtext section is still relevant, so let's keep it. Another thing I
wanted to mention is that the JSON examples in the documentation don't show
nested sections, but if it did, it would better illustrate the flexibility
of the format, so let's please get that in there.

Not in this page, though. I believe there's another page that shows a
medical example or something.

-amin
