### ISSUE TITLE
Describe behavior of characters_before and characters_after

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-docs#292]
Setting these values causes Vectara to "greedily" capture the entire sentence that contains the captured characters. This is surprising if all you expected was a set of characters up to the configured limit. We can address this in the docs to minimize confusion.

![image](https://github.com/vectara/vectara-docs/assets/1238659/b62fea83-1124-4dc2-ac7b-05b883c444e5)

**Comment by pwoznic** [comment]
This has been added to the [topic](https://docs.vectara.com/docs/rest-api/query) in a recent yaml update.

<img width="680" alt="image" src="https://github.com/vectara/vectara-docs/assets/25128922/c1c55916-2e20-45c5-a364-e8ee05110b53">

**Comment by cjcenizal** [comment]
Thanks!
