### ISSUE TITLE
Wrong parameters referred to in the doc

### ISSUE THREAD

**Issue by forrestbao** [vectara/vectara-docs#307]
### Pages

Many pages 

### Description

There are some wrong parameters used in our doc. For example, 

https://github.com/vectara/vectara-docs/blob/51070aeb6663d00abc7145e750717f68a09cd316/www/docs/api-reference/search-apis/search.md?plain=1#L302-L303

but we don't have the `responseChars` parameter. Is it `max_response_characters`? 

Can we please brush up the entire document to minimize such discrepancies?

**Comment by pwoznic** [comment]
I have been actively updating the long-form docs and API reference so that we do not have these discrepancies.

**Comment by forrestbao** [comment]
thanks Paul.

**Comment by eskibars** [comment]
@pwoznic is this still outstanding?  Let's chat in our 1:1 if the answer is "yes"

**Comment by pwoznic** [comment]
@eskibars We can chat about it. :) The API playground updates were fixed last month and a few long-form topics have minor changes in an upcoming PR.
