### ISSUE TITLE
"Edit this page" link from REST examples pages leads to a 404

### ISSUE THREAD

**Issue by mjang** [vectara/vectara-docs#50]
### Pages

All REST examples pages

### Description

When you select "Edit this page" from any of the noted pages, you get a 404 error. Example:

From https://docs.vectara.com/docs/getting-started-samples/RestUploadFile.java, I scroll down, select "Edit this page", I'm redirected to https://github.com/vectara/vectara-docs/tree/main/www/docs/getting-started-samples/RestUploadFile.java.md

This is an interesting problem, as anyone who wants to edit this page would have to understand that it pulls its source from two other pages.

**Comment by eskibars** [comment]
Thank you for the report!  This is an interesting problem indeed :)

There's a Docusaurus plugin at play here that doesn't really account for the display format when "edit on GitHub" is in play.

I'm pretty sure there's a solution that's not too terribly difficult to implement -- either adding some custom JS or some other modification to the import (ideally) or less ideally: just removing or modifying the edit link for these imported pages.

I'll have a look myself, but if anyone else has ideas, I'd love to hear them!
