### ISSUE TITLE
Wrong python code when using FILE_UPLOAD playground example

### ISSUE THREAD

**Issue by ofermend** [vectara/vectara-docs#75]
### Pages

N/A

### Description

Have been helping a customer with some questions about how to use the API.
In the process I've been play with the playground (https://docs.vectara.com/docs/rest-api/file-upload) and noticed that if I add metadata it shows up in CURL:
curl -L -X POST 'https://api.vectara.io/v1/upload?c=1865746051&o=3' \
-H 'Content-Type: multipart/form-data' \
-H 'Accept: application/json' \
-H 'x-api-key: <API_KEY>' \
-F 'file=@"/path/to/file"' \
-F 'doc_metadata="{'\''reportID#'\'': '\''12345678.pdf'\''}"'
But does not show in the Python:
import requests
url = "https://api.vectara.io/v1/upload?c=1865746051&o=3"
payload={}
files=[
  ('file',('file',open('/path/to/file','rb'),'application/octet-stream'))
]
headers = {
  'Content-Type': 'multipart/form-data',
  'Accept': 'application/json',
  'x-api-key': '<API_KEY>'
}
response = requests.request("POST", url, headers=headers, data=payload, files=files)
print(response.text)

Per @eskibars 

"The PAN plugin powers our playground and we're using it in a very vanilla way, and just bringing in our own OAS definition with no real custom code on top of it. I have not done a thorough debugging of these issues, but my suspicion is that several of these issues lie in the PAN plugin. it didn't look like they've got many artifacts using file uploads, and that's generally an underdeveloped area of all of OAS, so it wouldn't surprise me to see a lot of solutions have problems with multi-part file uploads with metadata"

**Comment by pwoznic** [comment]
The PAN plugin was updated a few days ago. Does this issue still occur?

**Comment by eskibars** [comment]
@pwoznic can you please check this first by copy/pasting into a python script and trying?  I think it still is broken

**Comment by ozgurozkan123** [comment]
I also confirm Python example is not working.
