### ISSUE TITLE
Timeout in REST calls

### ISSUE THREAD

**Issue by aamirbutt** [vectara/vectara-docs#92]
### Idea

We can specify timeout in the REST calls using `grpc-timeout`
This was [proposed to a customer here](https://discuss.vectara.com/t/vectara-search-works-but-curl-times-out/282/6?u=aamir), and it worked for them.

It would be great if we could add this to our documentation for two reasons.
1) For completion sake.
2) The name `grpc-timeout` header is a very cryptic name for rest call, and very hard for somebody to figure out on their own.

**Comment by pwoznic** [comment]
Sure, I can add this header to the docs but I have a couple questions:

- Does this apply to all REST calls and if so, should I create a generic note in each REST topic that says something like "If you get a timeout error, specify a value for grpc-timeout in the header"
- Do you have guidance on what values they should specify and why these values? For example, is there a good value for customers to use all the time, or are there different values for different scenarios?

**Comment by aamirbutt** [comment]
Re 1: This does apply to all REST calls, but we would like to  mention this ideally for calls that can potentially take longer. Some from the top of my head are: CreateCorpus, IndexData, FileUpload, Query/Summarization. 

Re 2: 30S seems to be a long enough timeout for most of the calls I mentioned above.

**Comment by pwoznic** [comment]
> Re 1: This does apply to all REST calls, but we would like to mention this ideally for calls that can potentially take longer. Some from the top of my head are: CreateCorpus, IndexData, FileUpload, Query/Summarization.
> 
> Re 2: 30S seems to be a long enough timeout for most of the calls I mentioned above.

Thank you for the details! I will update the docs and attach a PR to this issue.
