### ISSUE TITLE
Bearer Token is confusing in API Playground

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-docs#96]
Given that we have App Clients and API Keys, how do I use these to generate a value to fill out "Bearer Token"?

![image](https://github.com/vectara/vectara-docs/assets/1238659/fa7f8225-e27a-4305-a7ec-27cd434b1464)

**Comment by cjcenizal** [comment]
Potentially related -- I tried reading https://docs.vectara.com/docs/api-reference/auth-apis/oauth-2 to learn more and it left me confused. Under "Obtain a WT token", the docs begin with "Before continuing, you'll need the OAuth 2.0 token endpoint..." and gives some information on how to get the endpoint. But then it ends there. I was surprised because "Before continuing" implies there will be guidance on how to continue obtaining a JWT token but instead the docs just kind of stop.

**Comment by pwoznic** [comment]
I just created PR 100 that updates the OAuth 2.0 topic with more clarity.
